#!/bin/sh
for sync in async sync; do
prog="test-axing-parser-$sync";
for xml in tests/xml/*.xml; do
    txt=tests/results/`basename $xml .xml`.txt;
    test -f $txt && ./$prog $xml | cmp -s - $txt || (echo $prog:$xml; exit 1; ) || break;
done
done
for uri in tests/uri/*.txt; do
    ./test-axing-uri-resolver $uri || break;
done
